blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"

urlpatterns = [
    path("", render_posts, name="posts"),
    path("<int:post_id>", post_detail, name="post_detail"),
]

proyecto_portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
#--
from django.conf.urls.static import static
from django.conf import settings
#--

from portafolio import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("blog/", include("blog.urls"))
]

#--
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#--

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(datetime.date.today)
    
    

portafolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portafolio/images/')
    url = URLField(blank=True)
    
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request, "posts.html", {"posts": posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "post_detail.html", {"post": post})

portafolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, "home.html", {"projects": projects})

blog/templates/post_detail.html
{% extends "layout.html" %}

{% block content %}

<div class="text-center">
    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-muted">{{post.date|date:"F jS Y"}}</h3>

    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">

    <div class="my-4">
        <p>{{post.description|safe}}</p>
    </div>
</div>

{% endblock %}

blog/templates/posts.html
{% extends "layout.html" %}

{% block content %}

<h1>My Posts</h1>

{% for post in posts %}

<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
            </div>
            <div class="col-9">
                <h2>{{post.title}}</h2>
                {% comment %} <h3>{{post.date}}</h3> {% endcomment %}
                <p>{{post.description|striptags|truncatechars:100}}</p>
        
                <p>{{post.date|date:"M d y"|upper}}</p>

                <a href="{% url "blog:post_detail" post.id %}" class="btn btn-primary">{{post.title}}</a>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

portafolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="row bg-black p-3 m-4">
    <div class="col-md-4 p-4">
        <img src="{% static 'portfolio/programador.jpg' %}" alt="" class="card-img-top">
    </div>
    <div class="col-md-8 my-auto">
        <h1><strong>Cristian Paladines</strong></h1>
        <h3>Full Stack Developer</h3>
        <p>Soy desarrollador Full Stack, con conocimientos en Fronted y Backend con proyectos en Node.JS, FastAPI, Django, MySQL y Angular. Adicionalmente estoy interesado en Machine Learning, data Science y Artificial Intelligence. Experiencia en desarrollo web, innovación, diseño de proyectos usando metodología ágil SCRUM y Disign Thinking. En mi tiempo libre me gusta trabajar en proyectos personales y aprender nuevas tecnologías.</p>
        <a href="{% static 'portfolio/curriculumVitae-Ejemplos.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3" target="_blank">Download CV</a>
    </div>
</header>

<div class="row my-4 text-center">

    <h3 class="p-4"><strong>My projects</strong></h3>
    <p class="p-4">Como desarrollador Full Stack, he trabajado en varios proyectos que me han permitido mejorar mis habilidades técnicas y creativas. Cada uno de mis proyectos ha sido un desafío único, y he aprendido mucho en el camino.</p>

    {% for project in projects %}

    <div class="col-md-4 p-2">
        <div class="card bg-black card-project">
            <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top">
            <div class="card-body">
                <h2>{{project.title}}</h2>
                <p>{{project.description}}</p>
                
                {% if project.url  %}
                <a href="{{project.url}}" class="btn btn-info rounded-0 btn-sm" target="_blank">{{project.url|striptags|truncatechars:35}}</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% endfor %}

    {% endblock %}
</div>

portafolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My_Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"> 
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Code&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "main.css" %}">
</head>
<body class="text-light">

    {% include 'partials/navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>

    {% comment %} <footer>Footer</footer> {% endcomment %}

</body>
</html>

portafolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">My_Portfolio</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url "blog:posts" %}">About_Projects</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/curriculumVitae-Ejemplos.pdf' %}" target="_blank">Download CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>